2024-11-29 12:59:44,889 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'init' at Fri, 29 Nov 2024 12:59:44 +0000. Up 6.62 seconds.
2024-11-29 12:59:44,889 - main.py[DEBUG]: No kernel command line url found.
2024-11-29 12:59:44,889 - main.py[DEBUG]: Closing stdin.
2024-11-29 12:59:44,889 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=False)
2024-11-29 12:59:44,890 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-11-29 12:59:44,908 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=False)
2024-11-29 12:59:44,908 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-11-29 12:59:44,910 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-instance (recursive=False)
2024-11-29 12:59:44,911 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-11-29 12:59:44,923 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-once (recursive=False)
2024-11-29 12:59:44,923 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-11-29 12:59:44,927 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/per-boot (recursive=False)
2024-11-29 12:59:44,928 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts (recursive=True)
2024-11-29 12:59:44,931 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/scripts/vendor (recursive=False)
2024-11-29 12:59:44,931 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-11-29 12:59:44,948 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/seed (recursive=False)
2024-11-29 12:59:44,948 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-11-29 12:59:44,966 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances (recursive=False)
2024-11-29 12:59:44,966 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-11-29 12:59:44,984 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/handlers (recursive=False)
2024-11-29 12:59:44,984 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud (recursive=True)
2024-11-29 12:59:45,004 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/sem (recursive=False)
2024-11-29 12:59:45,004 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data (recursive=False)
2024-11-29 12:59:45,005 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init (recursive=True)
2024-11-29 12:59:45,005 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/sem (recursive=False)
2024-11-29 12:59:45,005 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [640] 0 bytes
2024-11-29 12:59:45,006 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-11-29 12:59:45,006 - util.py[DEBUG]: Restoring selinux mode for /var/log/cloud-init.log (recursive=False)
2024-11-29 12:59:45,007 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 0:4
2024-11-29 12:59:45,007 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 3 bytes
2024-11-29 12:59:45,007 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-11-29 12:59:45,008 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/python-version (recursive=False)
2024-11-29 12:59:45,009 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:45,023 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:45,033 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2024-11-29 12:59:45,047 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2024-11-29 12:59:45,048 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2024-11-29 12:59:45,048 - stages.py[DEBUG]: no cache found
2024-11-29 12:59:45,048 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2024-11-29 12:59:45,048 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-11-29 12:59:45,069 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-11-29 12:59:45,069 - __init__.py[DEBUG]: Looking for data source in: ['Ec2', 'None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2024-11-29 12:59:45,083 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceEc2', 'DataSourceNone']
2024-11-29 12:59:45,083 - handlers.py[DEBUG]: start: init-network/search-Ec2: searching for network data from DataSourceEc2
2024-11-29 12:59:45,083 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceEc2.DataSourceEc2'>
2024-11-29 12:59:45,083 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2024-11-29 12:59:45,083 - util.py[DEBUG]: Reading from /sys/hypervisor/uuid (quiet=False)
2024-11-29 12:59:45,083 - util.py[DEBUG]: Read 37 bytes from /sys/hypervisor/uuid
2024-11-29 12:59:45,083 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/product_serial
2024-11-29 12:59:45,083 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/chassis_asset_tag
2024-11-29 12:59:45,083 - dmi.py[DEBUG]: querying dmi data /sys/class/dmi/id/sys_vendor
2024-11-29 12:59:45,083 - DataSourceEc2.py[DEBUG]: strict_mode: warn, cloud_name=aws cloud_platform=ec2
2024-11-29 12:59:45,084 - util.py[DEBUG]: Skipping DNS checks of IP address 169.254.169.254
2024-11-29 12:59:45,084 - util.py[DEBUG]: Resolving URL: http://169.254.169.254:80 took 0.000 seconds
2024-11-29 12:59:45,084 - util.py[DEBUG]: Skipping DNS checks of IP address fd00:ec2::254
2024-11-29 12:59:45,084 - util.py[DEBUG]: Resolving URL: http://[fd00:ec2::254]:80 took 0.000 seconds
2024-11-29 12:59:45,084 - DataSourceEc2.py[DEBUG]: Fetching Ec2 IMDSv2 API Token
2024-11-29 12:59:45,084 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/latest/api/token' with {'url': 'http://169.254.169.254:80/latest/api/token', 'allow_redirects': True, 'method': 'PUT', 'timeout': 50.0, 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token-ttl-seconds': 'REDACTED'}} configuration
2024-11-29 12:59:45,103 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/latest/api/token (200, 56b) after 1 attempts
2024-11-29 12:59:45,104 - DataSourceEc2.py[DEBUG]: Using metadata source: 'http://169.254.169.254:80'
2024-11-29 12:59:45,104 - url_helper.py[DEBUG]: [0/1] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'headers': {'User-Agent': 'Cloud-Init/22.2.2', 'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,107 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-11-29 12:59:45,107 - DataSourceEc2.py[DEBUG]: Found preferred metadata version 2021-03-23
2024-11-29 12:59:45,107 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/user-data' with {'url': 'http://169.254.169.254:80/2021-03-23/user-data', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,109 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/user-data (200, 2448b) after 1 attempts
2024-11-29 12:59:45,109 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,111 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ (200, 305b) after 1 attempts
2024-11-29 12:59:45,111 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,123 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ (200, 8b) after 1 attempts
2024-11-29 12:59:45,123 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,124 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/ami (200, 4b) after 1 attempts
2024-11-29 12:59:45,125 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,127 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/block-device-mapping/root (200, 9b) after 1 attempts
2024-11-29 12:59:45,127 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,129 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/ (200, 12b) after 1 attempts
2024-11-29 12:59:45,129 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,130 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/ (200, 17b) after 1 attempts
2024-11-29 12:59:45,130 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,133 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/history (200, 2b) after 1 attempts
2024-11-29 12:59:45,133 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,135 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/events/maintenance/scheduled (200, 2b) after 1 attempts
2024-11-29 12:59:45,135 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,143 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/ (200, 26b) after 1 attempts
2024-11-29 12:59:45,143 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/iam/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,146 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/iam/info (200, 216b) after 1 attempts
2024-11-29 12:59:45,146 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,147 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ (200, 4b) after 1 attempts
2024-11-29 12:59:45,147 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,149 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/ (200, 26b) after 1 attempts
2024-11-29 12:59:45,149 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,153 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/identity-credentials/ec2/info (200, 98b) after 1 attempts
2024-11-29 12:59:45,153 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,154 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/ (200, 7b) after 1 attempts
2024-11-29 12:59:45,154 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,156 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/metrics/vhostmd (200, 38b) after 1 attempts
2024-11-29 12:59:45,156 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,163 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/ (200, 11b) after 1 attempts
2024-11-29 12:59:45,163 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,165 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/ (200, 5b) after 1 attempts
2024-11-29 12:59:45,165 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,167 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/ (200, 18b) after 1 attempts
2024-11-29 12:59:45,167 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,173 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/ (200, 230b) after 1 attempts
2024-11-29 12:59:45,173 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/ipv4-associations/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/ipv4-associations/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,180 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/ipv4-associations/ (200, 13b) after 1 attempts
2024-11-29 12:59:45,180 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/ipv4-associations/44.204.46.182' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/ipv4-associations/44.204.46.182', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,182 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/ipv4-associations/44.204.46.182 (200, 13b) after 1 attempts
2024-11-29 12:59:45,182 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/device-number' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/device-number', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,184 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/device-number (200, 1b) after 1 attempts
2024-11-29 12:59:45,184 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/interface-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/interface-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,193 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/interface-id (200, 21b) after 1 attempts
2024-11-29 12:59:45,193 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,194 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/local-hostname (200, 29b) after 1 attempts
2024-11-29 12:59:45,194 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/local-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/local-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,197 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/local-ipv4s (200, 13b) after 1 attempts
2024-11-29 12:59:45,197 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,203 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/mac (200, 17b) after 1 attempts
2024-11-29 12:59:45,203 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/owner-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/owner-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,204 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/owner-id (200, 12b) after 1 attempts
2024-11-29 12:59:45,204 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,213 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/public-hostname (200, 41b) after 1 attempts
2024-11-29 12:59:45,213 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/public-ipv4s' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/public-ipv4s', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,214 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/public-ipv4s (200, 13b) after 1 attempts
2024-11-29 12:59:45,215 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/security-group-ids' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/security-group-ids', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,216 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/security-group-ids (200, 20b) after 1 attempts
2024-11-29 12:59:45,216 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,223 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/security-groups (200, 56b) after 1 attempts
2024-11-29 12:59:45,223 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/subnet-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/subnet-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,225 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/subnet-id (200, 15b) after 1 attempts
2024-11-29 12:59:45,225 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/subnet-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/subnet-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,226 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/subnet-ipv4-cidr-block (200, 14b) after 1 attempts
2024-11-29 12:59:45,226 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/vpc-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/vpc-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,233 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/vpc-id (200, 12b) after 1 attempts
2024-11-29 12:59:45,233 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/vpc-ipv4-cidr-block' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/vpc-ipv4-cidr-block', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,234 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/vpc-ipv4-cidr-block (200, 13b) after 1 attempts
2024-11-29 12:59:45,235 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/vpc-ipv4-cidr-blocks' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/vpc-ipv4-cidr-blocks', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,236 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/network/interfaces/macs/12:1b:b3:a0:df:f9/vpc-ipv4-cidr-blocks (200, 13b) after 1 attempts
2024-11-29 12:59:45,236 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,243 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/ (200, 45b) after 1 attempts
2024-11-29 12:59:45,243 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,244 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone (200, 10b) after 1 attempts
2024-11-29 12:59:45,244 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,248 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/availability-zone-id (200, 8b) after 1 attempts
2024-11-29 12:59:45,248 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/placement/region', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,252 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/placement/region (200, 9b) after 1 attempts
2024-11-29 12:59:45,253 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,254 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/ (200, 16b) after 1 attempts
2024-11-29 12:59:45,254 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/domain', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,256 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/domain (200, 13b) after 1 attempts
2024-11-29 12:59:45,256 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/services/partition', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,263 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/services/partition (200, 3b) after 1 attempts
2024-11-29 12:59:45,263 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,264 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-id (200, 21b) after 1 attempts
2024-11-29 12:59:45,264 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,266 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-launch-index (200, 1b) after 1 attempts
2024-11-29 12:59:45,266 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,268 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/ami-manifest-path (200, 9b) after 1 attempts
2024-11-29 12:59:45,268 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,273 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/hostname (200, 29b) after 1 attempts
2024-11-29 12:59:45,273 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-action', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,277 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-action (200, 4b) after 1 attempts
2024-11-29 12:59:45,277 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,283 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-id (200, 19b) after 1 attempts
2024-11-29 12:59:45,283 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,285 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-life-cycle (200, 9b) after 1 attempts
2024-11-29 12:59:45,285 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/instance-type', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,286 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/instance-type (200, 8b) after 1 attempts
2024-11-29 12:59:45,287 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,293 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-hostname (200, 29b) after 1 attempts
2024-11-29 12:59:45,293 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,294 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/local-ipv4 (200, 13b) after 1 attempts
2024-11-29 12:59:45,295 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/mac' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/mac', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,296 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/mac (200, 17b) after 1 attempts
2024-11-29 12:59:45,296 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/profile' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/profile', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,303 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/profile (200, 11b) after 1 attempts
2024-11-29 12:59:45,303 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-hostname', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,305 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-hostname (200, 41b) after 1 attempts
2024-11-29 12:59:45,305 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,307 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/public-ipv4 (200, 13b) after 1 attempts
2024-11-29 12:59:45,307 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/reservation-id', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,313 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/reservation-id (200, 19b) after 1 attempts
2024-11-29 12:59:45,313 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups' with {'url': 'http://169.254.169.254:80/2021-03-23/meta-data/security-groups', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,314 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/meta-data/security-groups (200, 56b) after 1 attempts
2024-11-29 12:59:45,315 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,316 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity (200, 32b) after 1 attempts
2024-11-29 12:59:45,316 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,323 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/document (200, 477b) after 1 attempts
2024-11-29 12:59:45,323 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,324 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/pkcs7 (200, 1171b) after 1 attempts
2024-11-29 12:59:45,324 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,326 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/rsa2048 (200, 1491b) after 1 attempts
2024-11-29 12:59:45,326 - url_helper.py[DEBUG]: [0/6] open 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature' with {'url': 'http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature', 'allow_redirects': True, 'method': 'GET', 'timeout': 5.0, 'headers': {'X-aws-ec2-metadata-token': 'REDACTED'}} configuration
2024-11-29 12:59:45,333 - url_helper.py[DEBUG]: Read from http://169.254.169.254:80/2021-03-23/dynamic/instance-identity/signature (200, 174b) after 1 attempts
2024-11-29 12:59:45,333 - util.py[DEBUG]: Crawl of metadata service took 0.250 seconds
2024-11-29 12:59:45,335 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-aws - wb: [644] 4 bytes
2024-11-29 12:59:45,335 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-11-29 12:59:45,336 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/cloud-id-aws (recursive=False)
2024-11-29 12:59:45,336 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-aws'
2024-11-29 12:59:45,337 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmp5z9bxv9o) - w: [600] 11946 bytes/chars
2024-11-29 12:59:45,337 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpihvsmvbl) - w: [644] 7804 bytes/chars
2024-11-29 12:59:45,337 - handlers.py[DEBUG]: finish: init-network/search-Ec2: SUCCESS: found network data from DataSourceEc2
2024-11-29 12:59:45,337 - stages.py[INFO]: Loaded datasource DataSourceEc2 - DataSourceEc2
2024-11-29 12:59:45,337 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-11-29 12:59:45,337 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-11-29 12:59:45,338 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,354 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-11-29 12:59:45,354 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-11-29 12:59:45,354 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,356 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-11-29 12:59:45,356 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-11-29 12:59:45,356 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,358 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-11-29 12:59:45,358 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-11-29 12:59:45,358 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,360 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-11-29 12:59:45,361 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-11-29 12:59:45,361 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,372 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-11-29 12:59:45,372 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,372 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-11-29 12:59:45,373 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2024-11-29 12:59:45,373 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/i-0a6923d06430c5604'
2024-11-29 12:59:45,374 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604 (recursive=True)
2024-11-29 12:59:45,376 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/handlers (recursive=False)
2024-11-29 12:59:45,377 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604 (recursive=True)
2024-11-29 12:59:45,380 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/scripts (recursive=False)
2024-11-29 12:59:45,380 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604 (recursive=True)
2024-11-29 12:59:45,393 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem (recursive=False)
2024-11-29 12:59:45,394 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/i-0a6923d06430c5604/datasource (quiet=False)
2024-11-29 12:59:45,394 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/datasource - wb: [644] 29 bytes
2024-11-29 12:59:45,394 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/datasource (recursive=False)
2024-11-29 12:59:45,395 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/datasource (recursive=False)
2024-11-29 12:59:45,395 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 29 bytes
2024-11-29 12:59:45,397 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-11-29 12:59:45,397 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-datasource (recursive=False)
2024-11-29 12:59:45,397 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2024-11-29 12:59:45,397 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2024-11-29 12:59:45,397 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2024-11-29 12:59:45,399 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-11-29 12:59:45,399 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/instance-id (recursive=False)
2024-11-29 12:59:45,399 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2024-11-29 12:59:45,400 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-11-29 12:59:45,400 - util.py[DEBUG]: Restoring selinux mode for /run/cloud-init/.instance-id (recursive=False)
2024-11-29 12:59:45,400 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2024-11-29 12:59:45,400 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-11-29 12:59:45,401 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-instance-id (recursive=False)
2024-11-29 12:59:45,401 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 12513 bytes
2024-11-29 12:59:45,402 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/obj.pkl (recursive=False)
2024-11-29 12:59:45,407 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/obj.pkl (recursive=False)
2024-11-29 12:59:45,407 - main.py[DEBUG]: [net] init will now be targeting instance id: i-0a6923d06430c5604. new=True
2024-11-29 12:59:45,407 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-11-29 12:59:45,407 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-11-29 12:59:45,407 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,425 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-11-29 12:59:45,425 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-11-29 12:59:45,425 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,426 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-11-29 12:59:45,426 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-11-29 12:59:45,426 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,428 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-11-29 12:59:45,428 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-11-29 12:59:45,428 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,430 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-11-29 12:59:45,430 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-11-29 12:59:45,430 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,431 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-11-29 12:59:45,431 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,431 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-11-29 12:59:45,432 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-11-29 12:59:45,442 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-11-29 12:59:45,442 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2024-11-29 12:59:45,442 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enX0/address
2024-11-29 12:59:45,442 - util.py[DEBUG]: Reading from /sys/class/net/enX0/name_assign_type (quiet=False)
2024-11-29 12:59:45,442 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enX0/name_assign_type
2024-11-29 12:59:45,442 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2024-11-29 12:59:45,442 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enX0/address
2024-11-29 12:59:45,443 - util.py[DEBUG]: Reading from /sys/class/net/enX0/carrier (quiet=False)
2024-11-29 12:59:45,443 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enX0/carrier
2024-11-29 12:59:45,443 - util.py[DEBUG]: Reading from /sys/class/net/lo/addr_assign_type (quiet=False)
2024-11-29 12:59:45,443 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/lo/addr_assign_type
2024-11-29 12:59:45,443 - util.py[DEBUG]: Reading from /sys/class/net/lo/uevent (quiet=False)
2024-11-29 12:59:45,443 - util.py[DEBUG]: Read 23 bytes from /sys/class/net/lo/uevent
2024-11-29 12:59:45,443 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2024-11-29 12:59:45,443 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2024-11-29 12:59:45,444 - __init__.py[DEBUG]: ovs-vsctl not in PATH; not detecting Open vSwitch interfaces
2024-11-29 12:59:45,444 - util.py[DEBUG]: Reading from /sys/class/net/lo/device/device (quiet=False)
2024-11-29 12:59:45,444 - util.py[DEBUG]: Reading from /sys/class/net/enX0/addr_assign_type (quiet=False)
2024-11-29 12:59:45,444 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enX0/addr_assign_type
2024-11-29 12:59:45,444 - util.py[DEBUG]: Reading from /sys/class/net/enX0/uevent (quiet=False)
2024-11-29 12:59:45,444 - util.py[DEBUG]: Read 25 bytes from /sys/class/net/enX0/uevent
2024-11-29 12:59:45,444 - util.py[DEBUG]: Reading from /sys/class/net/enX0/address (quiet=False)
2024-11-29 12:59:45,444 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/enX0/address
2024-11-29 12:59:45,444 - util.py[DEBUG]: Reading from /sys/class/net/enX0/device/device (quiet=False)
2024-11-29 12:59:45,444 - util.py[DEBUG]: Reading from /sys/class/net/lo/type (quiet=False)
2024-11-29 12:59:45,444 - util.py[DEBUG]: Read 4 bytes from /sys/class/net/lo/type
2024-11-29 12:59:45,444 - util.py[DEBUG]: Reading from /sys/class/net/enX0/type (quiet=False)
2024-11-29 12:59:45,444 - util.py[DEBUG]: Read 2 bytes from /sys/class/net/enX0/type
2024-11-29 12:59:45,444 - stages.py[DEBUG]: network config disabled by system_cfg
2024-11-29 12:59:45,444 - stages.py[INFO]: network config is disabled by system_cfg
2024-11-29 12:59:45,444 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2024-11-29 12:59:45,444 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2024-11-29 12:59:45,444 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/user-data.txt - wb: [600] 2448 bytes
2024-11-29 12:59:45,445 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/user-data.txt (recursive=False)
2024-11-29 12:59:45,445 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/user-data.txt (recursive=False)
2024-11-29 12:59:45,446 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,453 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/user-data.txt.i - wb: [600] 2470 bytes
2024-11-29 12:59:45,453 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/user-data.txt.i (recursive=False)
2024-11-29 12:59:45,454 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/user-data.txt.i (recursive=False)
2024-11-29 12:59:45,454 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data.txt - wb: [600] 0 bytes
2024-11-29 12:59:45,455 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data.txt (recursive=False)
2024-11-29 12:59:45,456 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data.txt (recursive=False)
2024-11-29 12:59:45,456 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data.txt.i - wb: [600] 308 bytes
2024-11-29 12:59:45,457 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data.txt.i (recursive=False)
2024-11-29 12:59:45,457 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data.txt.i (recursive=False)
2024-11-29 12:59:45,457 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data2.txt - wb: [600] 0 bytes
2024-11-29 12:59:45,458 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data2.txt (recursive=False)
2024-11-29 12:59:45,458 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data2.txt (recursive=False)
2024-11-29 12:59:45,459 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data2.txt.i - wb: [600] 308 bytes
2024-11-29 12:59:45,460 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data2.txt.i (recursive=False)
2024-11-29 12:59:45,461 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/vendor-data2.txt.i (recursive=False)
2024-11-29 12:59:45,472 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-11-29 12:59:45,472 - cc_set_hostname.py[DEBUG]: Setting the hostname to ip-172-31-86-102.ec2.internal (ip-172-31-86-102)
2024-11-29 12:59:45,472 - subp.py[DEBUG]: Running command ['hostnamectl', 'set-hostname', 'ip-172-31-86-102.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:45,607 - __init__.py[DEBUG]: Non-persistently setting the system hostname to ip-172-31-86-102.ec2.internal
2024-11-29 12:59:45,608 - subp.py[DEBUG]: Running command ['hostname', 'ip-172-31-86-102.ec2.internal'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:45,612 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/set-hostname (via temporary file /var/lib/cloud/data/tmp3rgvp3og) - w: [644] 78 bytes/chars
2024-11-29 12:59:45,613 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/consume_data - wb: [644] 25 bytes
2024-11-29 12:59:45,613 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/consume_data (recursive=False)
2024-11-29 12:59:45,614 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/consume_data (recursive=False)
2024-11-29 12:59:45,615 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/consume_data'>)
2024-11-29 12:59:45,615 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2024-11-29 12:59:45,615 - launch_index.py[DEBUG]: Discarding 0 multipart messages which do not match launch index 0
2024-11-29 12:59:45,616 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2024-11-29 12:59:45,616 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2024-11-29 12:59:45,616 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2024-11-29 12:59:45,616 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2024-11-29 12:59:45,616 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2024-11-29 12:59:45,617 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2024-11-29 12:59:45,617 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2024-11-29 12:59:45,617 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2024-11-29 12:59:45,617 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,617 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,617 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,617 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,617 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,617 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2024-11-29 12:59:45,617 - __init__.py[DEBUG]: {'Content-Type': 'text/cloud-config; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="cloud-config.txt"'}
2024-11-29 12:59:45,617 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, cloud-config.txt, 3) with frequency once-per-instance
2024-11-29 12:59:45,617 - util.py[DEBUG]: Attempting to load yaml from string of length 104 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,618 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2024-11-29 12:59:45,619 - __init__.py[DEBUG]: {'Content-Type': 'text/x-shellscript; charset="us-ascii"', 'MIME-Version': '1.0', 'Content-Transfer-Encoding': '7bit', 'Content-Disposition': 'attachment; filename="user-data.txt"'}
2024-11-29 12:59:45,619 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (text/x-shellscript, user-data.txt, 2) with frequency once-per-instance
2024-11-29 12:59:45,619 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/scripts/user-data.txt - wb: [700] 1799 bytes
2024-11-29 12:59:45,619 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/scripts/user-data.txt (recursive=False)
2024-11-29 12:59:45,620 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/scripts/user-data.txt (recursive=False)
2024-11-29 12:59:45,620 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2024-11-29 12:59:45,620 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/cloud-config.txt - wb: [600] 154 bytes
2024-11-29 12:59:45,621 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/cloud-config.txt (recursive=False)
2024-11-29 12:59:45,621 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/cloud-config.txt (recursive=False)
2024-11-29 12:59:45,621 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,621 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,621 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,621 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,621 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2024-11-29 12:59:45,621 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2024-11-29 12:59:45,632 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2024-11-29 12:59:45,632 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2024-11-29 12:59:45,632 - stages.py[DEBUG]: no vendordata from datasource
2024-11-29 12:59:45,632 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2024-11-29 12:59:45,632 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2024-11-29 12:59:45,632 - stages.py[DEBUG]: no vendordata2 from datasource
2024-11-29 12:59:45,632 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2024-11-29 12:59:45,632 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2024-11-29 12:59:45,633 - util.py[DEBUG]: Read 2553 bytes from /etc/cloud/cloud.cfg
2024-11-29 12:59:45,633 - util.py[DEBUG]: Attempting to load yaml from string of length 2553 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,640 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg (quiet=False)
2024-11-29 12:59:45,640 - util.py[DEBUG]: Read 174 bytes from /etc/cloud/cloud.cfg.d/40_selinux-reboot.cfg
2024-11-29 12:59:45,640 - util.py[DEBUG]: Attempting to load yaml from string of length 174 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,640 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg (quiet=False)
2024-11-29 12:59:45,640 - util.py[DEBUG]: Read 591 bytes from /etc/cloud/cloud.cfg.d/10_aws_dnfvars.cfg
2024-11-29 12:59:45,640 - util.py[DEBUG]: Attempting to load yaml from string of length 591 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,642 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2024-11-29 12:59:45,642 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2024-11-29 12:59:45,652 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,654 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg (quiet=False)
2024-11-29 12:59:45,654 - util.py[DEBUG]: Read 237 bytes from /etc/cloud/cloud.cfg.d/01_amazon-ec2.cfg
2024-11-29 12:59:45,654 - util.py[DEBUG]: Attempting to load yaml from string of length 237 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,655 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2024-11-29 12:59:45,655 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,655 - util.py[DEBUG]: loaded blob returned None, returning default.
2024-11-29 12:59:45,656 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-11-29 12:59:45,656 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-11-29 12:59:45,657 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,657 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,657 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,744 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2024-11-29 12:59:45,744 - util.py[DEBUG]: Read 154 bytes from /var/lib/cloud/instance/cloud-config.txt
2024-11-29 12:59:45,744 - util.py[DEBUG]: Attempting to load yaml from string of length 154 with allowed root types (<class 'dict'>,)
2024-11-29 12:59:45,746 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2024-11-29 12:59:45,747 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 16660 bytes
2024-11-29 12:59:45,752 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/obj.pkl (recursive=False)
2024-11-29 12:59:45,753 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/obj.pkl (recursive=False)
2024-11-29 12:59:45,753 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2024-11-29 12:59:45,753 - main.py[DEBUG]: no di_report found in config.
2024-11-29 12:59:45,763 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,763 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,765 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,765 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,768 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,768 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,772 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,772 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,775 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,775 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,777 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,777 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,783 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,783 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,795 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,795 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,797 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,797 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,802 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,802 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,804 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,804 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,812 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,812 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,814 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,814 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,816 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,817 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,819 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,819 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,832 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:45,832 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:45,834 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-11-29 12:59:45,835 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2024-11-29 12:59:45,835 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2024-11-29 12:59:45,835 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7fa8d0265e20>)
2024-11-29 12:59:45,835 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2024-11-29 12:59:45,835 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2024-11-29 12:59:45,835 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2024-11-29 12:59:45,835 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2024-11-29 12:59:45,835 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_seed_random - wb: [644] 25 bytes
2024-11-29 12:59:45,837 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_seed_random (recursive=False)
2024-11-29 12:59:45,838 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_seed_random (recursive=False)
2024-11-29 12:59:45,838 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_seed_random'>)
2024-11-29 12:59:45,838 - cc_seed_random.py[DEBUG]: no command provided
2024-11-29 12:59:45,839 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2024-11-29 12:59:45,839 - modules.py[DEBUG]: Running module bootcmd (<module 'cloudinit.config.cc_bootcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_bootcmd.py'>) with frequency always
2024-11-29 12:59:45,839 - handlers.py[DEBUG]: start: init-network/config-bootcmd: running config-bootcmd with frequency always
2024-11-29 12:59:45,839 - helpers.py[DEBUG]: Running config-bootcmd using lock (<cloudinit.helpers.DummyLock object at 0x7fa8d0265e20>)
2024-11-29 12:59:45,839 - cc_bootcmd.py[DEBUG]: Skipping module named bootcmd, no 'bootcmd' key in configuration
2024-11-29 12:59:45,839 - handlers.py[DEBUG]: finish: init-network/config-bootcmd: SUCCESS: config-bootcmd ran successfully
2024-11-29 12:59:45,839 - modules.py[DEBUG]: Running module write-files (<module 'cloudinit.config.cc_write_files' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_files.py'>) with frequency once-per-instance
2024-11-29 12:59:45,839 - handlers.py[DEBUG]: start: init-network/config-write-files: running config-write-files with frequency once-per-instance
2024-11-29 12:59:45,839 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_write_files - wb: [644] 25 bytes
2024-11-29 12:59:45,840 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_write_files (recursive=False)
2024-11-29 12:59:45,840 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_write_files (recursive=False)
2024-11-29 12:59:45,840 - helpers.py[DEBUG]: Running config-write-files using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_write_files'>)
2024-11-29 12:59:45,841 - cc_write_files.py[DEBUG]: Skipping module named write-files, no/empty 'write_files' key in configuration
2024-11-29 12:59:45,841 - handlers.py[DEBUG]: finish: init-network/config-write-files: SUCCESS: config-write-files ran successfully
2024-11-29 12:59:45,841 - modules.py[DEBUG]: Running module write-metadata (<module 'cloudinit.config.cc_write_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_write_metadata.py'>) with frequency once-per-instance
2024-11-29 12:59:45,841 - handlers.py[DEBUG]: start: init-network/config-write-metadata: running config-write-metadata with frequency once-per-instance
2024-11-29 12:59:45,841 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_write_metadata - wb: [644] 25 bytes
2024-11-29 12:59:45,841 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_write_metadata (recursive=False)
2024-11-29 12:59:45,842 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_write_metadata (recursive=False)
2024-11-29 12:59:45,852 - helpers.py[DEBUG]: Running config-write-metadata using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_write_metadata'>)
2024-11-29 12:59:45,852 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsregion - wb: [644] 9 bytes
2024-11-29 12:59:45,854 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-11-29 12:59:45,854 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsregion (recursive=False)
2024-11-29 12:59:45,855 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsregion to 0:0
2024-11-29 12:59:45,855 - util.py[DEBUG]: Writing to /etc/dnf/vars/awsdomain - wb: [644] 13 bytes
2024-11-29 12:59:45,855 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-11-29 12:59:45,855 - util.py[DEBUG]: Restoring selinux mode for /etc/dnf/vars/awsdomain (recursive=False)
2024-11-29 12:59:45,856 - util.py[DEBUG]: Changing the ownership of /etc/dnf/vars/awsdomain to 0:0
2024-11-29 12:59:45,856 - handlers.py[DEBUG]: finish: init-network/config-write-metadata: SUCCESS: config-write-metadata ran successfully
2024-11-29 12:59:45,856 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2024-11-29 12:59:45,856 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2024-11-29 12:59:45,856 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7fa8d0265f10>)
2024-11-29 12:59:45,856 - cc_growpart.py[DEBUG]: No 'growpart' entry in cfg.  Using default: {'mode': 'auto', 'devices': ['/'], 'ignore_growroot_disabled': False}
2024-11-29 12:59:45,856 - subp.py[DEBUG]: Running command ['growpart', '--help'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:45,863 - util.py[DEBUG]: Reading from /proc/2021/mountinfo (quiet=False)
2024-11-29 12:59:45,863 - util.py[DEBUG]: Read 2816 bytes from /proc/2021/mountinfo
2024-11-29 12:59:45,863 - util.py[DEBUG]: Reading from /sys/class/block/xvda1/partition (quiet=False)
2024-11-29 12:59:45,863 - util.py[DEBUG]: Read 2 bytes from /sys/class/block/xvda1/partition
2024-11-29 12:59:45,864 - util.py[DEBUG]: Reading from /sys/devices/vbd-51712/block/xvda/dev (quiet=False)
2024-11-29 12:59:45,864 - util.py[DEBUG]: Read 6 bytes from /sys/devices/vbd-51712/block/xvda/dev
2024-11-29 12:59:45,864 - subp.py[DEBUG]: Running command ['growpart', '--dry-run', '/dev/xvda', '1'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:45,954 - util.py[DEBUG]: resize_devices took 0.092 seconds
2024-11-29 12:59:45,954 - cc_growpart.py[DEBUG]: '/' NOCHANGE: no change necessary (/dev/xvda, 1)
2024-11-29 12:59:45,955 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2024-11-29 12:59:45,955 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2024-11-29 12:59:45,955 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2024-11-29 12:59:45,955 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7fa8d0265fd0>)
2024-11-29 12:59:45,955 - util.py[DEBUG]: Reading from /proc/2021/mountinfo (quiet=False)
2024-11-29 12:59:45,955 - util.py[DEBUG]: Read 2816 bytes from /proc/2021/mountinfo
2024-11-29 12:59:45,955 - cc_resizefs.py[DEBUG]: resize_info: dev=/dev/xvda1 mnt_point=/ path=/
2024-11-29 12:59:45,955 - cc_resizefs.py[DEBUG]: Resizing / (xfs) using xfs_growfs /
2024-11-29 12:59:45,956 - util.py[DEBUG]: Forked child 2159 who will run callback log_time
2024-11-29 12:59:45,956 - cc_resizefs.py[DEBUG]: Resizing (via forking) root filesystem (type=xfs, val=noblock)
2024-11-29 12:59:45,957 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2024-11-29 12:59:45,957 - modules.py[DEBUG]: Running module disk_setup (<module 'cloudinit.config.cc_disk_setup' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disk_setup.py'>) with frequency once-per-instance
2024-11-29 12:59:45,957 - handlers.py[DEBUG]: start: init-network/config-disk_setup: running config-disk_setup with frequency once-per-instance
2024-11-29 12:59:45,957 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_disk_setup - wb: [644] 25 bytes
2024-11-29 12:59:45,959 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_disk_setup (recursive=False)
2024-11-29 12:59:45,961 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_disk_setup (recursive=False)
2024-11-29 12:59:45,961 - helpers.py[DEBUG]: Running config-disk_setup using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_disk_setup'>)
2024-11-29 12:59:45,961 - handlers.py[DEBUG]: finish: init-network/config-disk_setup: SUCCESS: config-disk_setup ran successfully
2024-11-29 12:59:45,961 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2024-11-29 12:59:45,961 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2024-11-29 12:59:45,961 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_mounts - wb: [644] 25 bytes
2024-11-29 12:59:45,962 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_mounts (recursive=False)
2024-11-29 12:59:45,972 - subp.py[DEBUG]: Running command ('xfs_growfs', '/') with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:45,975 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_mounts (recursive=False)
2024-11-29 12:59:45,976 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_mounts'>)
2024-11-29 12:59:45,982 - cc_mounts.py[DEBUG]: mounts configuration is []
2024-11-29 12:59:45,982 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2024-11-29 12:59:45,983 - util.py[DEBUG]: Read 217 bytes from /etc/fstab
2024-11-29 12:59:45,983 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2024-11-29 12:59:45,983 - DataSourceEc2.py[DEBUG]: Unable to convert ephemeral0 to a device
2024-11-29 12:59:45,983 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2024-11-29 12:59:45,983 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2024-11-29 12:59:45,983 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2024-11-29 12:59:45,983 - DataSourceEc2.py[DEBUG]: Unable to convert swap to a device
2024-11-29 12:59:45,983 - cc_mounts.py[DEBUG]: changed default device swap => None
2024-11-29 12:59:45,983 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2024-11-29 12:59:45,983 - cc_mounts.py[DEBUG]: no need to setup swap
2024-11-29 12:59:45,983 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2024-11-29 12:59:45,983 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2024-11-29 12:59:45,983 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_hostname.py'>) with frequency always
2024-11-29 12:59:45,983 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency always
2024-11-29 12:59:45,983 - helpers.py[DEBUG]: Running config-set_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fa8d0e979d0>)
2024-11-29 12:59:45,983 - util.py[DEBUG]: Reading from /var/lib/cloud/data/set-hostname (quiet=False)
2024-11-29 12:59:45,983 - util.py[DEBUG]: Read 78 bytes from /var/lib/cloud/data/set-hostname
2024-11-29 12:59:45,984 - cc_set_hostname.py[DEBUG]: No hostname changes. Skipping set-hostname
2024-11-29 12:59:45,984 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2024-11-29 12:59:45,984 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2024-11-29 12:59:45,984 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2024-11-29 12:59:45,984 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7fa8d0265fd0>)
2024-11-29 12:59:45,984 - cc_update_hostname.py[DEBUG]: Updating hostname to ip-172-31-86-102.ec2.internal (ip-172-31-86-102)
2024-11-29 12:59:45,984 - subp.py[DEBUG]: Running command ['hostname'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:45,992 - util.py[DEBUG]: backgrounded Resizing took 0.020 seconds
2024-11-29 12:59:45,993 - __init__.py[DEBUG]: Attempting to update hostname to ip-172-31-86-102.ec2.internal in 1 files
2024-11-29 12:59:45,994 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-hostname - wb: [644] 29 bytes
2024-11-29 12:59:45,994 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-11-29 12:59:46,003 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/data/previous-hostname (recursive=False)
2024-11-29 12:59:46,004 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2024-11-29 12:59:46,004 - modules.py[DEBUG]: Running module update_etc_hosts (<module 'cloudinit.config.cc_update_etc_hosts' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_update_etc_hosts.py'>) with frequency always
2024-11-29 12:59:46,004 - handlers.py[DEBUG]: start: init-network/config-update_etc_hosts: running config-update_etc_hosts with frequency always
2024-11-29 12:59:46,004 - helpers.py[DEBUG]: Running config-update_etc_hosts using lock (<cloudinit.helpers.DummyLock object at 0x7fa8d0265e20>)
2024-11-29 12:59:46,004 - cc_update_etc_hosts.py[DEBUG]: Configuration option 'manage_etc_hosts' is not set, not managing /etc/hosts in module update_etc_hosts
2024-11-29 12:59:46,004 - handlers.py[DEBUG]: finish: init-network/config-update_etc_hosts: SUCCESS: config-update_etc_hosts ran successfully
2024-11-29 12:59:46,004 - modules.py[DEBUG]: Running module ca-certs (<module 'cloudinit.config.cc_ca_certs' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ca_certs.py'>) with frequency once-per-instance
2024-11-29 12:59:46,004 - handlers.py[DEBUG]: start: init-network/config-ca-certs: running config-ca-certs with frequency once-per-instance
2024-11-29 12:59:46,004 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ca_certs - wb: [644] 25 bytes
2024-11-29 12:59:46,005 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ca_certs (recursive=False)
2024-11-29 12:59:46,006 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ca_certs (recursive=False)
2024-11-29 12:59:46,006 - helpers.py[DEBUG]: Running config-ca-certs using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ca_certs'>)
2024-11-29 12:59:46,006 - cc_ca_certs.py[DEBUG]: Skipping module named ca-certs, no 'ca_certs' key in configuration
2024-11-29 12:59:46,006 - handlers.py[DEBUG]: finish: init-network/config-ca-certs: SUCCESS: config-ca-certs ran successfully
2024-11-29 12:59:46,006 - modules.py[DEBUG]: Running module rsyslog (<module 'cloudinit.config.cc_rsyslog' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_rsyslog.py'>) with frequency once-per-instance
2024-11-29 12:59:46,006 - handlers.py[DEBUG]: start: init-network/config-rsyslog: running config-rsyslog with frequency once-per-instance
2024-11-29 12:59:46,006 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_rsyslog - wb: [644] 24 bytes
2024-11-29 12:59:46,007 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_rsyslog (recursive=False)
2024-11-29 12:59:46,007 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_rsyslog (recursive=False)
2024-11-29 12:59:46,007 - helpers.py[DEBUG]: Running config-rsyslog using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_rsyslog'>)
2024-11-29 12:59:46,007 - cc_rsyslog.py[DEBUG]: Skipping module named rsyslog, no 'rsyslog' key in configuration
2024-11-29 12:59:46,007 - handlers.py[DEBUG]: finish: init-network/config-rsyslog: SUCCESS: config-rsyslog ran successfully
2024-11-29 12:59:46,007 - modules.py[DEBUG]: Running module selinux (<module 'cloudinit.config.cc_selinux' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_selinux.py'>) with frequency once-per-instance
2024-11-29 12:59:46,007 - handlers.py[DEBUG]: start: init-network/config-selinux: running config-selinux with frequency once-per-instance
2024-11-29 12:59:46,008 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_selinux - wb: [644] 25 bytes
2024-11-29 12:59:46,008 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_selinux (recursive=False)
2024-11-29 12:59:46,009 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_selinux (recursive=False)
2024-11-29 12:59:46,009 - helpers.py[DEBUG]: Running config-selinux using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_selinux'>)
2024-11-29 12:59:46,017 - cc_selinux.py[DEBUG]: Current SELinux state is enabled
2024-11-29 12:59:46,017 - cc_selinux.py[DEBUG]: Current SELinux mode is permissive
2024-11-29 12:59:46,017 - cc_selinux.py[DEBUG]: Configured SELinux mode is permissive
2024-11-29 12:59:46,017 - cc_selinux.py[DEBUG]: Current SELinux policy is targeted
2024-11-29 12:59:46,017 - cc_selinux.py[DEBUG]: No SELinux configuration, skipping
2024-11-29 12:59:46,017 - handlers.py[DEBUG]: finish: init-network/config-selinux: SUCCESS: config-selinux ran successfully
2024-11-29 12:59:46,017 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2024-11-29 12:59:46,017 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2024-11-29 12:59:46,018 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_users_groups - wb: [644] 25 bytes
2024-11-29 12:59:46,018 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_users_groups (recursive=False)
2024-11-29 12:59:46,019 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_users_groups (recursive=False)
2024-11-29 12:59:46,019 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_users_groups'>)
2024-11-29 12:59:46,019 - __init__.py[INFO]: User ec2-user already exists, skipping.
2024-11-29 12:59:46,020 - subp.py[DEBUG]: Running command ['passwd', '-l', 'ec2-user'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:46,068 - util.py[DEBUG]: Reading from /etc/sudoers (quiet=False)
2024-11-29 12:59:46,069 - util.py[DEBUG]: Read 4375 bytes from /etc/sudoers
2024-11-29 12:59:46,070 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d (recursive=False)
2024-11-29 12:59:46,071 - util.py[DEBUG]: Writing to /etc/sudoers.d/90-cloud-init-users - ab: [None] 59 bytes
2024-11-29 12:59:46,072 - util.py[DEBUG]: Restoring selinux mode for /etc/sudoers.d/90-cloud-init-users (recursive=False)
2024-11-29 12:59:46,072 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2024-11-29 12:59:46,072 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2024-11-29 12:59:46,072 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2024-11-29 12:59:46,073 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ssh - wb: [644] 25 bytes
2024-11-29 12:59:46,073 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ssh (recursive=False)
2024-11-29 12:59:46,074 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ssh (recursive=False)
2024-11-29 12:59:46,074 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ssh'>)
2024-11-29 12:59:46,077 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:46,094 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-11-29 12:59:46,102 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:46,118 - util.py[DEBUG]: Restoring selinux mode for /etc/ssh (recursive=True)
2024-11-29 12:59:46,133 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2024-11-29 12:59:46,133 - util.py[DEBUG]: Read 116 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2024-11-29 12:59:46,133 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2024-11-29 12:59:46,133 - util.py[DEBUG]: Read 196 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2024-11-29 12:59:46,133 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-11-29 12:59:46,134 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-11-29 12:59:46,135 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh to 1000:1000
2024-11-29 12:59:46,135 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=False)
2024-11-29 12:59:46,135 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-11-29 12:59:46,136 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-11-29 12:59:46,136 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-11-29 12:59:46,136 - util.py[DEBUG]: Changing the ownership of /home/ec2-user/.ssh/authorized_keys to 1000:1000
2024-11-29 12:59:46,136 - util.py[DEBUG]: Reading from /home/ec2-user/.ssh/authorized_keys (quiet=False)
2024-11-29 12:59:46,136 - util.py[DEBUG]: Read 0 bytes from /home/ec2-user/.ssh/authorized_keys
2024-11-29 12:59:46,136 - util.py[DEBUG]: Writing to /home/ec2-user/.ssh/authorized_keys - wb: [600] 0 bytes
2024-11-29 12:59:46,137 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-11-29 12:59:46,137 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh/authorized_keys (recursive=False)
2024-11-29 12:59:46,137 - util.py[DEBUG]: Restoring selinux mode for /home/ec2-user/.ssh (recursive=True)
2024-11-29 12:59:46,138 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-11-29 12:59:46,138 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-11-29 12:59:46,138 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-11-29 12:59:46,140 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-11-29 12:59:46,140 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-11-29 12:59:46,140 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-11-29 12:59:46,140 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2024-11-29 12:59:46,140 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2024-11-29 12:59:46,140 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2024-11-29 12:59:46,140 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2024-11-29 12:59:46,140 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-11-29 12:59:46,140 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh/authorized_keys (recursive=False)
2024-11-29 12:59:46,140 - util.py[DEBUG]: Restoring selinux mode for /root/.ssh (recursive=True)
2024-11-29 12:59:46,141 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2024-11-29 12:59:46,141 - main.py[DEBUG]: Ran 17 modules with 0 failures
2024-11-29 12:59:46,142 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpnll5sfs_) - w: [644] 485 bytes/chars
2024-11-29 12:59:46,142 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-11-29 12:59:46,152 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2024-11-29 12:59:46,152 - util.py[DEBUG]: cloud-init mode 'init' took 1.391 seconds (1.41)
2024-11-29 12:59:46,152 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2024-11-29 12:59:47,064 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:config' at Fri, 29 Nov 2024 12:59:46 +0000. Up 8.75 seconds.
2024-11-29 12:59:47,072 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,072 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,078 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,078 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,082 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,082 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,084 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,084 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,092 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,092 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,094 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,094 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,097 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,097 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,102 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,102 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,104 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,104 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,106 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,106 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,107 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-11-29 12:59:47,108 - modules.py[INFO]: Skipping modules 'ssh-import-id' because they are not verified on distro 'amazon'.  To run anyway, add them to 'unverified_modules' in config.
2024-11-29 12:59:47,108 - modules.py[DEBUG]: Running module keyboard (<module 'cloudinit.config.cc_keyboard' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_keyboard.py'>) with frequency once-per-instance
2024-11-29 12:59:47,108 - handlers.py[DEBUG]: start: modules-config/config-keyboard: running config-keyboard with frequency once-per-instance
2024-11-29 12:59:47,108 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_keyboard - wb: [644] 25 bytes
2024-11-29 12:59:47,110 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_keyboard (recursive=False)
2024-11-29 12:59:47,122 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_keyboard (recursive=False)
2024-11-29 12:59:47,122 - helpers.py[DEBUG]: Running config-keyboard using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_keyboard'>)
2024-11-29 12:59:47,122 - cc_keyboard.py[DEBUG]: Skipping module named keyboard, no 'keyboard' section found
2024-11-29 12:59:47,123 - handlers.py[DEBUG]: finish: modules-config/config-keyboard: SUCCESS: config-keyboard ran successfully
2024-11-29 12:59:47,123 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2024-11-29 12:59:47,123 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2024-11-29 12:59:47,123 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_locale - wb: [644] 24 bytes
2024-11-29 12:59:47,123 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_locale (recursive=False)
2024-11-29 12:59:47,124 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_locale (recursive=False)
2024-11-29 12:59:47,124 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_locale'>)
2024-11-29 12:59:47,124 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-11-29 12:59:47,124 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-11-29 12:59:47,124 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2024-11-29 12:59:47,125 - util.py[DEBUG]: Reading from /etc/locale.conf (quiet=False)
2024-11-29 12:59:47,125 - util.py[DEBUG]: Read 17 bytes from /etc/locale.conf
2024-11-29 12:59:47,125 - util.py[DEBUG]: Writing to /etc/locale.conf - wb: [644] 17 bytes
2024-11-29 12:59:47,127 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-11-29 12:59:47,128 - util.py[DEBUG]: Restoring selinux mode for /etc/locale.conf (recursive=False)
2024-11-29 12:59:47,129 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2024-11-29 12:59:47,129 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2024-11-29 12:59:47,129 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2024-11-29 12:59:47,129 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_set_passwords - wb: [644] 25 bytes
2024-11-29 12:59:47,129 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_set_passwords (recursive=False)
2024-11-29 12:59:47,129 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_set_passwords (recursive=False)
2024-11-29 12:59:47,143 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_set_passwords'>)
2024-11-29 12:59:47,144 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'sshd'] with allowed return codes [0] (shell=False, capture=True)
2024-11-29 12:59:47,165 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2024-11-29 12:59:47,165 - util.py[DEBUG]: Read 3854 bytes from /etc/ssh/sshd_config
2024-11-29 12:59:47,166 - ssh_util.py[DEBUG]: line 65: option PasswordAuthentication already set to no
2024-11-29 12:59:47,166 - cc_set_passwords.py[DEBUG]: No need to restart SSH service, PasswordAuthentication not updated.
2024-11-29 12:59:47,166 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2024-11-29 12:59:47,166 - modules.py[DEBUG]: Running module yum-variables (<module 'cloudinit.config.cc_yum_variables' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_variables.py'>) with frequency once-per-instance
2024-11-29 12:59:47,166 - handlers.py[DEBUG]: start: modules-config/config-yum-variables: running config-yum-variables with frequency once-per-instance
2024-11-29 12:59:47,166 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_yum_variables - wb: [644] 25 bytes
2024-11-29 12:59:47,167 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_yum_variables (recursive=False)
2024-11-29 12:59:47,167 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_yum_variables (recursive=False)
2024-11-29 12:59:47,168 - helpers.py[DEBUG]: Running config-yum-variables using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_yum_variables'>)
2024-11-29 12:59:47,168 - cc_yum_variables.py[INFO]: handling yum-variables
2024-11-29 12:59:47,168 - cc_yum_variables.py[INFO]: cfg = {'cloud_final_modules': [['scripts-user', 'always']], 'repo_releasever': 2023.6, 'repo_upgrade': 'none', 'power_state': {'delay': 'now', 'mode': 'reboot', 'message': 'Rebooting machine to apply SELinux kernel commandline setting', 'condition': 'test -f /run/cloud-init-selinux-reboot'}, 'write_metadata': [{'path': '/etc/dnf/vars/awsregion', 'data': [{'identity': 'region'}, 'default']}, {'path': '/etc/dnf/vars/awsdomain', 'data': [{'metadata': 'services/domain'}, 'amazonaws.com']}], '_log': ['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n", '[handler_cloudLogHandler]\nclass=handlers.SysLogHandler\nlevel=DEBUG\nformatter=simpleFormatter\nargs=("/dev/log", handlers.SysLogHandler.LOG_USER)\n'], 'log_cfgs': [['[loggers]\nkeys=root,cloudinit\n\n[handlers]\nkeys=consoleHandler,cloudLogHandler\n\n[formatters]\nkeys=simpleFormatter,arg0Formatter\n\n[logger_root]\nlevel=DEBUG\nhandlers=consoleHandler,cloudLogHandler\n\n[logger_cloudinit]\nlevel=DEBUG\nqualname=cloudinit\nhandlers=\npropagate=1\n\n[handler_consoleHandler]\nclass=StreamHandler\nlevel=WARNING\nformatter=arg0Formatter\nargs=(sys.stderr,)\n\n[formatter_arg0Formatter]\nformat=%(asctime)s - %(filename)s[%(levelname)s]: %(message)s\n\n[formatter_simpleFormatter]\nformat=[CLOUDINIT] %(filename)s[%(levelname)s]: %(message)s\n', "[handler_cloudLogHandler]\nclass=FileHandler\nlevel=DEBUG\nformatter=arg0Formatter\nargs=('/var/log/cloud-init.log', 'a', 'UTF-8')\n"]], 'output': {'all': '| tee -a /var/log/cloud-init-output.log'}, 'network': {'config': 'disabled'}, 'datasource_list': ['Ec2', 'None'], 'datasource': {'Ec2': {'metadata_urls': ['http://169.254.169.254:80', 'http://[fd00:ec2::254]:80'], 'apply_full_imds_network_config': False}}, 'ssh_genkeytypes': ['ed25519', 'ecdsa'], 'users': ['default'], 'disable_root': True, 'mount_default_fields': [None, None, 'auto', 'defaults,nofail', '0', '2'], 'resize_rootfs': 'noblock', 'resize_rootfs_tmp': '/dev', 'ssh_pwauth': False, 'preserve_hostname': False, 'cloud_init_modules': ['migrator', 'seed_random', 'bootcmd', 'write-files', 'write-metadata', 'growpart', 'resizefs', 'disk_setup', 'mounts', 'set_hostname', 'update_hostname', 'update_etc_hosts', 'ca-certs', 'rsyslog', 'selinux', 'users-groups', 'ssh'], 'cloud_config_modules': ['ssh-import-id', 'keyboard', 'locale', 'set-passwords', 'yum-variables', 'yum-add-repo', 'ntp', 'timezone', 'disable-ec2-metadata', 'runcmd'], 'def_log_file': '/var/log/cloud-init.log', 'syslog_fix_perms': ['syslog:adm', 'root:adm', 'root:wheel', 'root:root'], 'vendor_data': {'enabled': True, 'prefix': []}, 'vendor_data2': {'enabled': True, 'prefix': []}}
2024-11-29 12:59:47,168 - cc_yum_variables.py[INFO]: No yum vars to delete
2024-11-29 12:59:47,168 - cc_yum_variables.py[INFO]: No yum vars to set
2024-11-29 12:59:47,168 - handlers.py[DEBUG]: finish: modules-config/config-yum-variables: SUCCESS: config-yum-variables ran successfully
2024-11-29 12:59:47,168 - modules.py[DEBUG]: Running module yum-add-repo (<module 'cloudinit.config.cc_yum_add_repo' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_yum_add_repo.py'>) with frequency once-per-instance
2024-11-29 12:59:47,168 - handlers.py[DEBUG]: start: modules-config/config-yum-add-repo: running config-yum-add-repo with frequency once-per-instance
2024-11-29 12:59:47,168 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_yum_add_repo - wb: [644] 25 bytes
2024-11-29 12:59:47,168 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_yum_add_repo (recursive=False)
2024-11-29 12:59:47,169 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_yum_add_repo (recursive=False)
2024-11-29 12:59:47,169 - helpers.py[DEBUG]: Running config-yum-add-repo using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_yum_add_repo'>)
2024-11-29 12:59:47,169 - cc_yum_add_repo.py[DEBUG]: Skipping module named yum-add-repo, no 'yum_repos' configuration found
2024-11-29 12:59:47,169 - handlers.py[DEBUG]: finish: modules-config/config-yum-add-repo: SUCCESS: config-yum-add-repo ran successfully
2024-11-29 12:59:47,169 - modules.py[DEBUG]: Running module ntp (<module 'cloudinit.config.cc_ntp' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_ntp.py'>) with frequency once-per-instance
2024-11-29 12:59:47,169 - handlers.py[DEBUG]: start: modules-config/config-ntp: running config-ntp with frequency once-per-instance
2024-11-29 12:59:47,169 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ntp - wb: [644] 25 bytes
2024-11-29 12:59:47,170 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ntp (recursive=False)
2024-11-29 12:59:47,170 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ntp (recursive=False)
2024-11-29 12:59:47,171 - helpers.py[DEBUG]: Running config-ntp using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_ntp'>)
2024-11-29 12:59:47,171 - cc_ntp.py[DEBUG]: Skipping module named ntp, not present or disabled by cfg
2024-11-29 12:59:47,171 - handlers.py[DEBUG]: finish: modules-config/config-ntp: SUCCESS: config-ntp ran successfully
2024-11-29 12:59:47,171 - modules.py[DEBUG]: Running module timezone (<module 'cloudinit.config.cc_timezone' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_timezone.py'>) with frequency once-per-instance
2024-11-29 12:59:47,171 - handlers.py[DEBUG]: start: modules-config/config-timezone: running config-timezone with frequency once-per-instance
2024-11-29 12:59:47,171 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_timezone - wb: [644] 25 bytes
2024-11-29 12:59:47,171 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_timezone (recursive=False)
2024-11-29 12:59:47,183 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_timezone (recursive=False)
2024-11-29 12:59:47,183 - helpers.py[DEBUG]: Running config-timezone using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_timezone'>)
2024-11-29 12:59:47,183 - cc_timezone.py[DEBUG]: Skipping module named timezone, no 'timezone' specified
2024-11-29 12:59:47,183 - handlers.py[DEBUG]: finish: modules-config/config-timezone: SUCCESS: config-timezone ran successfully
2024-11-29 12:59:47,183 - modules.py[DEBUG]: Running module disable-ec2-metadata (<module 'cloudinit.config.cc_disable_ec2_metadata' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_disable_ec2_metadata.py'>) with frequency always
2024-11-29 12:59:47,183 - handlers.py[DEBUG]: start: modules-config/config-disable-ec2-metadata: running config-disable-ec2-metadata with frequency always
2024-11-29 12:59:47,183 - helpers.py[DEBUG]: Running config-disable-ec2-metadata using lock (<cloudinit.helpers.DummyLock object at 0x7f8be75f0cd0>)
2024-11-29 12:59:47,183 - cc_disable_ec2_metadata.py[DEBUG]: Skipping module named disable-ec2-metadata, disabling the ec2 route not enabled
2024-11-29 12:59:47,183 - handlers.py[DEBUG]: finish: modules-config/config-disable-ec2-metadata: SUCCESS: config-disable-ec2-metadata ran successfully
2024-11-29 12:59:47,183 - modules.py[DEBUG]: Running module runcmd (<module 'cloudinit.config.cc_runcmd' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_runcmd.py'>) with frequency once-per-instance
2024-11-29 12:59:47,183 - handlers.py[DEBUG]: start: modules-config/config-runcmd: running config-runcmd with frequency once-per-instance
2024-11-29 12:59:47,184 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_runcmd - wb: [644] 25 bytes
2024-11-29 12:59:47,184 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_runcmd (recursive=False)
2024-11-29 12:59:47,185 - util.py[DEBUG]: Restoring selinux mode for /var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_runcmd (recursive=False)
2024-11-29 12:59:47,185 - helpers.py[DEBUG]: Running config-runcmd using lock (<FileLock using file '/var/lib/cloud/instances/i-0a6923d06430c5604/sem/config_runcmd'>)
2024-11-29 12:59:47,185 - cc_runcmd.py[DEBUG]: Skipping module named runcmd, no 'runcmd' key in configuration
2024-11-29 12:59:47,185 - handlers.py[DEBUG]: finish: modules-config/config-runcmd: SUCCESS: config-runcmd ran successfully
2024-11-29 12:59:47,185 - main.py[DEBUG]: Ran 9 modules with 0 failures
2024-11-29 12:59:47,185 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpiz69nluy) - w: [644] 513 bytes/chars
2024-11-29 12:59:47,185 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-11-29 12:59:47,185 - util.py[DEBUG]: Read 10 bytes from /proc/uptime
2024-11-29 12:59:47,185 - util.py[DEBUG]: cloud-init mode 'modules' took 0.264 seconds (0.27)
2024-11-29 12:59:47,186 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2024-11-29 12:59:47,976 - util.py[DEBUG]: Cloud-init v. 22.2.2 running 'modules:final' at Fri, 29 Nov 2024 12:59:47 +0000. Up 9.66 seconds.
2024-11-29 12:59:47,992 - util.py[DEBUG]: Reading from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2024-11-29 12:59:47,993 - util.py[DEBUG]: Read 102081 bytes from /usr/lib/python3.9/site-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2024-11-29 12:59:47,994 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.amazon.Distro'>
2024-11-29 12:59:47,995 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3.9/site-packages/cloudinit/config/cc_scripts_user.py'>) with frequency always
2024-11-29 12:59:47,995 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency always
2024-11-29 12:59:47,995 - helpers.py[DEBUG]: Running config-scripts-user using lock (<cloudinit.helpers.DummyLock object at 0x7f96bb930f10>)
2024-11-29 12:59:47,995 - subp.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/user-data.txt'] with allowed return codes [0] (shell=False, capture=False)
2024-11-29 12:59:56,034 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2024-11-29 12:59:56,034 - main.py[DEBUG]: Ran 1 modules with 0 failures
2024-11-29 12:59:56,035 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp3o2rxrnu) - w: [644] 540 bytes/chars
2024-11-29 12:59:56,035 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpabqxf0bc) - w: [644] 64 bytes/chars
2024-11-29 12:59:56,035 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2024-11-29 12:59:56,035 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2024-11-29 12:59:56,035 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2024-11-29 12:59:56,035 - util.py[DEBUG]: cloud-init mode 'modules' took 8.194 seconds (8.20)
2024-11-29 12:59:56,035 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
